element%type%value
acourse%xpath%.//a[contains(text(),'Advanced Course')]
menu2%xpath%//div[@class = 'menutop m2']//span[contains(text(), 'Menu 2')]
gotoNext%xpath%.//span[contains(text(), 'Go Next')]
symbol%xpath%.//*[@id='symboldisplay']
name%xpath%.//*[@id='name']
passkey%xpath%.//*[@id='passkey']
proceed%xpath%.//*[@id='submit']
session%xpath%.//*[@id='session_id']
proceedfinal%xpath%.//a[contains(text(),'Proceed')]
download%xpath%.//a[contains(text(),'Download File')]
sign%xpath%.//*[@id='signature']
proceedend%xpath%//input[@value="Proceed"]