element%type%value
bcourse%xpath%.//a[contains(text(),'Basic Course')]
greenbox%xpath%.//*[@class='greenbox']
matchbox%xpath%.//*[@id='answer']
repaint%xpath%.//a[contains(text(),'Repaint Box 2')]
proceed%xpath%.//a[contains(text(),'Proceed')]
launch%xpath%.//a[contains(text(),'Launch Popup Window')]
data%xpath%.//*[@id='name']
submit%xpath%.//*[@id='submit']
genToken%xpath%.//a[contains(text(),'Generate Token')]
token%xpath%.//*[@id='token']